languageCode = "fr-FR"
languageName = "Français"
languageDirection = "ltr"
weight = 1

title = "Congo"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Un thème puissant pour Hugo basé sur Tailwind CSS."

[params.author]
  name = "Congo"
  image = "img/author.jpg"
  headline = "Un thème pas ordinaire !"
  bio = "Ceci est un exemple, le site est en cours de construction. :dog:"
  links = [
    { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
