languageCode = "fr-FR"
languageName = "Français"
languageDirection = "ltr"
weight = 1

title = "Aurélien Tondoux"
copyright = "&copy; 2025 Aurélien Tondoux"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["samples"]
  description = "Présentation de mon parcours d'ingénieur logiciel, de mes projets, produits et accomplissements"

[params.author]
  name = "Aurélien Tondoux"
  image = "img/author.jpg"
  headline = "Tech Lead • Développeur Full Stack"
  bio = "## bio ##"
  links = [
    { linkedin = "https://www.linkedin.com/in/atondoux" },
    { github = "https://github.com/atondoux" }
  ]
