path: /products
title: "Mes créations."
description: "Les produits numériques que j'ai conçus et développés."
links:
  - label: "Prendre un rendez-vous"
    to: "https://calendly.com/atondoux/30min/"
    target: "_blank"
    color: "neutral"
  - label: "Mon profil Malt"
    to: "https://www.malt.fr/profile/aurelientondoux"
    target: "_blank"
    color: "primary"
seo:
  title: "Produits - Aurélien Tondoux"
  description: "Produits numériques : Ortho Assistant, formations Spring Boot et plus encore."
