path: /products
title: My creations.
description: Digital products I have designed and developed.
links:
  - label: "Book an appointment"
    to: "https://calendly.com/atondoux/30min/"
    target: "_blank"
    color: "neutral"
seo:
  title: "Products - Aurélien Tondoux"
  description: "Discover the digital products I have designed and developed: Ortho Assistant, Spring Boot training, and more."
